dcc.Dropdown(
            id="well_statuses",
            options=[{"label": "All2 ", "value": "all"},
            {"label": "Active only2 ", "value": "active"},
            {"label": "Customize2 ", "value": "custom"}],
            multi=True,
            value=5,
            className="dcc_control",
        ),
        dcc.Checklist(
            id="lock_selector",
            options=[{"label": "Lock camera", "value": "locked"}],
            className="dcc_control",
            value=[],
        ),
        html.P("Filter by well type:", className="control_label"),
        dcc.RadioItems(
            id="well_type_selector",
            options=[
                {"label": "All ", "value": "all"},
                {"label": "Productive only ", "value": "productive"},
                {"label": "Customize ", "value": "custom"},
            ],
            value="productive",
            labelStyle={"display": "inline-block"},
            className="dcc_control",
        ),
        dcc.Dropdown(
            id="well_types",
            options=[{"label": "All ", "value": "all"},
            {"label": "Active only ", "value": "active"},
            {"label": "Customize ", "value": "custom"}],
            multi=True,
            value=3,
            className="dcc_control",
        ),
